### PR TITLE
WIP - New Strategy RemovePodsViolatingTopologySpreadConstraint

### LINKED ISSUE #146: Policy for Balancing Pods across topology domains
The currently well known topology domains labels on the nodes are 
- failure-domain.beta.kubernetes.io/region
- failure-domain.beta.kubernetes.io/zone

Descheduler currently supports the following options: `RemoveDuplicates` , `LowNodeUtilization`, `RemovePodsViolatingInterPodAntiAffinity` and `RemovePodsViolatingNodeAffinity`.  None of these options support balancing pods across topology domains. The closest one to mimic  this behavior would be LowNodeUtilization which basically based on two thresholds, evicts pods which don't fall between a range but is sub optimal. 

Currently there is a KEP for even pod spreading, but that will take some time to come in. In the meantime , we need a policy in descheduler which does  the following:-
- forms a topology domain which is combination of region and zone
- figures out nodes in the same bucket by using the bucket key in step 1
- selects which pods this policy applies based on a labelSelector
- finds buckets, where the difference in the number of pods(selected by labelSelector) in that bucket and any other bucket is maximum, and starts evicting pods in that bucket in the hopes that it will schedule on a node in a different bucket

### PR DESCRIPTION
**Pull request by seanmalloy**
This is a work in progress. It does not work yet. Fixes #146.

This PR has three commits:
* f79d007a94183e7fe20912a58f3de75825ee353b - original work by @krmayankk
* 4e08c15b7331a2a433cb70f3c8424f48197c6622 - documentation
* f4ccb5a781022fccd413ca719c3aaafd7668daec - incomplete code refactor

Task List:
- [x] Documentation
- [ ] Unit Tests
- [ ] New Code For Strategy

### CODE REVIEW

**Comment by seanmalloy** [comment]
I do not have time to finish off this PR. This was discussed during the SIG scheduling meeting today(August 27th). The commits in this PR can be used as a starting point for someone that has time to complete this feature.

/kind feature
/help

**Comment by damemi** [comment]
Commented in https://github.com/kubernetes-sigs/descheduler/issues/146#issuecomment-683784846, I'll pick up your commits in a new PR

**Comment by rhockenbury** [comment]
Any updates on this work?

**Comment by damemi** [comment]
Hi @rhockenbury, I'm working on this and will open a new PR for it soon (I got delayed from when I first commented that I'll pick it up, but now I have time to focus on it). It should be available in the v0.20 release of the descheduler.

**Review by damemi — COMMENTED** [review]
/close
closing for new PR here: https://github.com/kubernetes-sigs/descheduler/pull/413

**Pull request closed without merging**
