### PR TITLE
Helm chart - allow 'falsey' value in cmdOption

### PR DESCRIPTION
**Pull request by omerap12**
Fixed: #1371

### CODE REVIEW

**Review by a7i — COMMENTED** [review]
how would this work for flags such as `--v=4`?

**Comment by omerap12** [comment]
> how would this work for flags such as `--v=4`?

what do you mean?

**Comment by a7i** [comment]
My apologies, this is what I meant to say:

This implementation will work for: `--v=4` but it will not work for `--enable-http2` where it doesn't require a value

**Comment by omerap12** [comment]
> My apologies, this is what I meant to say:
> 
> This implementation will work for: `--v=4` but it will not work for `--enable-http2` where it doesn't require a value

yes, you are right. lemme fix it real quick

**Comment by omerap12** [comment]
Output example:
```shell
# Source: descheduler/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-descheduler
  labels:
    app.kubernetes.io/name: descheduler
    helm.sh/chart: descheduler-0.29.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.29.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-descheduler
subjects:
  - kind: ServiceAccount
    name: release-name-descheduler
    namespace: default
---
# Source: descheduler/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-descheduler
  namespace: default
  labels:
    app.kubernetes.io/name: descheduler
    helm.sh/chart: descheduler-0.29.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.29.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: descheduler
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: descheduler
        app.kubernetes.io/instance: release-name
      annotations:
        checksum/config: f35eff353cbeb8f608c03a0e9a21a65c6a12bbc3c7bccd407e5fc64709f3a935
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: release-name-descheduler
      containers:
        - name: descheduler
          image: "registry.k8s.io/descheduler/descheduler:v0.29.0"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/descheduler
          args:
            - --policy-config-file=/policy-dir/policy.yaml
            - --descheduling-interval=5m
            - --enable-https
            - --s=1
            - --v=0
            
          ports:
            - containerPort: 10258
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10258
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
      volumes:
        - name: policy-volume
          configMap:
            name: release-name-descheduler
```
For cronjob:
```shell
# Source: descheduler/templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: release-name-descheduler
  namespace: default
  labels:
    app.kubernetes.io/name: descheduler
    helm.sh/chart: descheduler-0.29.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.29.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: release-name-descheduler
          annotations:
            checksum/config: f35eff353cbeb8f608c03a0e9a21a65c6a12bbc3c7bccd407e5fc64709f3a935
          labels:
            app.kubernetes.io/name: descheduler
            app.kubernetes.io/instance: release-name
        spec:
          priorityClassName: system-cluster-critical
          serviceAccountName: release-name-descheduler
          restartPolicy: "Never"
          containers:
            - name: descheduler
              image: "registry.k8s.io/descheduler/descheduler:v0.29.0"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/descheduler
              args:
                - --policy-config-file=/policy-dir/policy.yaml
                - --enable-https
                - --s=1
                - --v=0
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 10258
                  scheme: HTTPS
                initialDelaySeconds: 3
                periodSeconds: 10
              resources:
                requests:
                  cpu: 500m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
              volumeMounts:
                - mountPath: /policy-dir
                  name: policy-volume
          volumes:
          - name: policy-volume
            configMap:
              name: release-name-descheduler
```
with the values:
```shell
cmdOptions:
  v: 0
  enable-https:
  s: 1
```

**Review by a7i — APPROVED** [review]
/lgtm

thank you for your contribution 🏆

**Pull request merged**
