### PR TITLE
pkg/descheduler/strategies: fix typo

### PR DESCRIPTION
**Pull request by invidian**
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>

### CODE REVIEW

**Comment by farah** [comment]
While you're at it can you also fix this one:

https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/pod/pods.go#L111

switcheds > switches

**Comment by farah** [comment]
It may be worth importing the script `hack/verify-spelling.sh` from from the kubernetes repo

**Comment by invidian** [comment]
>On a separate note, it may be worth importing the script hack/verify-spelling.sh from from the kubernetes repo

I was testing with `codespell`, so I probably didn't catch all of them.

**Review by seanmalloy — APPROVED** [review]

**Review by damemi — APPROVED** [review]
/approve
Thanks for fixing this!

**Comment by damemi** [comment]
Opened a PR to add the verify script in https://github.com/kubernetes-sigs/descheduler/pull/430

**Pull request merged**
