### PR TITLE
Release 1.22.1

### PR DESCRIPTION
**Pull request by a7i**
Summary of changes:
- Include changes from PR #632
- Update Helm chart to v0.22.1
- Update Docs and Manifests to use Image 0.22.1

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test
/hold
(just holding so that the chart-releaser doesn't automatically run before we are ready for it)

**Comment by a7i** [comment]
> /retest

@seanmalloy 
```
ERROR: failed to create cluster: failed to pull image "kindest/node:v1.20.10": command "docker pull kindest/node:v1.20.10" failed with error: exit status 1
```

Looks like the build is using [KUBERNETES_VERSION](https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh#L23) environment variable which is set to v1.20.10 and no matching Kind docker image exists ([ref](https://github.com/kubernetes-sigs/descheduler/blob/master/test/run-e2e-tests.sh#L29))

**Comment by damemi** [comment]
Sorry @a7i, I opened https://github.com/kubernetes/test-infra/pull/23815 to update this test

**Comment by seanmalloy** [comment]
kubernetes/test-infra#23815  is now merged.

/retest

**Pull request merged**
