### PR TITLE
Remove Travis CI Configuration

### PR DESCRIPTION
**Pull request by seanmalloy**
The e2e tests are now being run through Prow. Therefore the Travis CI
configuration can now be completely removed.

### CODE REVIEW

**Comment by seanmalloy** [comment]
/assign @damemi @ingvagabund 

@damemi please make the `pull-descheduler-test-e2e-k8s-master` CI check in the GitHub branch protection settings "Required". Thanks!

**Comment by damemi** [comment]
@seanmalloy I opened a PR in https://github.com/kubernetes/test-infra/pull/18303 to make this required
/hold
Until that merges

If you also want to work on it, we can update the test-e2e shell script to run a "version matrix" similar to what we had in travis. This approach was recommended by the sig-testing team on Slack, so it would be an acceptable solution to the fact that prow doesn't have this built in.

**Comment by ingvagabund** [comment]
I'd rather wait until the matrix is run in Prow as well before removing Travis config.

**Comment by damemi** [comment]
> I'd rather wait until the matrix is run in Prow as well before removing Travis config.

sgtm, @seanmalloy do you want to update this PR to do that? Seems fitting to make the switch here

**Comment by ingvagabund** [comment]
Once https://github.com/kubernetes/test-infra/pull/18305 merges, we can go ahead with the PR.

**Comment by seanmalloy** [comment]
/hold cancel

@damemi and @ingvagabund all the dependent pull requests have been merged. This is ready for review again.

**Pull request merged**
