### PR TITLE
Bump to k8s v0.30.0-alpha.3

### PR DESCRIPTION
**Pull request by pravarag**
Fixes: https://github.com/kubernetes-sigs/descheduler/issues/1357

Bump to the latest available alpha version.

### CODE REVIEW

**Comment by a7i** [comment]
@pravarag created a similar PR to see if build fails or not: https://github.com/kubernetes-sigs/descheduler/pull/1364

**Comment by a7i** [comment]
@jklaw90 @knelasevero should be ready for your review


/assign knelasevero

**Comment by jklaw90** [comment]
/lgtm
🎉

**Comment by a7i** [comment]
thank you @pravarag 🏆

**Pull request merged**
