### PR TITLE
Set default value for lease resource name

### PR DESCRIPTION
**Pull request by damemi**
Following https://github.com/kubernetes-sigs/descheduler/pull/876

### CODE REVIEW

**Review by JaneLiuL — COMMENTED** [review]
/lgtm

**Comment by JaneLiuL** [comment]
you should remove {}  in Line 49 @damemi

**Comment by iijimakazuyuki** [comment]
@damemi I opened new PR #882.

**Review by damemi — COMMENTED** [review]
/close
in favor of https://github.com/kubernetes-sigs/descheduler/pull/882

**Pull request closed without merging**
