### PR TITLE
Add seanmalloy to reviewers

### PR DESCRIPTION
**Pull request by seanmalloy**

### CODE REVIEW

**Comment by seanmalloy** [comment]
Look like in need to complete the steps [here](https://github.com/kubernetes/community/blob/master/community-membership.md#member) before I can be added to the OWNERS file.

**Comment by damemi** [comment]
@seanmalloy yeah, please link when you've got your PR open to add yourself to the org. If you need a sponsor I can +1 👍

**Comment by ravisantoshgudimetla** [comment]
Thanks for all the help @seanmalloy.  We're more than happy to have you as a reviewer :). Let us know once you complete the process.


For the record, Sean drove the changes needed for having an official descheduler container image hosted on kubernetes container registry is helping out in adding new strategies to descheduler.

**Comment by seanmalloy** [comment]
@ravisantoshgudimetla and @damemi I opened https://github.com/kubernetes/org/issues/1604 to apply for membership to the kubernetes-sigs organization.

**Comment by damemi** [comment]
@seanmalloy You may need another sponsor, as Ravi and I are both from Red Hat, but +1'd

**Comment by seanmalloy** [comment]
@damemi thanks for the info. I'm not sure who else I could add as a sponsor. So far I've only worked on the descheduler and interacted with people from RedHat on this project.

**Comment by seanmalloy** [comment]
@ravisantoshgudimetla I was able to join the `kubernetes-sigs` org. Please review again when you have some time.

**Pull request merged**
