### PR TITLE
Share links to all descheduler ehnacements proposals in the project repo

### LINKED ISSUE #646: Share links to all descheduler ehnacements proposals in the project repository
Let's allocate a place (e.g. in the README.md or in new proposals.md) for a list of all enhancements there are for a quick overview/lookup.

- [Descheduler v1alpha2 Design Proposal](https://docs.google.com/document/d/1S1JCh-0F-QCJvBBG-kbmXiHAJFF8doArhDIAKbOj93I/edit#heading=h.imbp1ctnc8lx)

### PR DESCRIPTION
**Pull request by JaneLiuL**
fix #646

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test
/approve

could add one for https://github.com/kubernetes-sigs/descheduler/issues/679 in here too

**Comment by JaneLiuL** [comment]
add #679 into proposals.md link?

**Comment by damemi** [comment]
sorry @JaneLiuL, thought I tagged this
/lgtm

**Pull request merged**
