### PR TITLE
bump to k8s 1.28 beta.0

### LINKED ISSUE #1191: Bump Kubernetes dependencies to v1.28.0-rc

### PR DESCRIPTION
**Pull request by a7i**
closes #1191 1191

went straight to beta instead of rc

### CODE REVIEW

**Comment by ingvagabund** [comment]
The master branch is our dev branch.
/approve

**Review by damemi — COMMENTED** [review]
/lgtm

**Comment by a7i** [comment]
@ingvagabund how would you want this to happen going forward?

**Comment by ingvagabund** [comment]
@a7i I meant "let's go". Just an empty phrase so I don't just type "approve" just like that :) All goes as it should go.

**Pull request merged**
