### PR TITLE
bump: k8s to 1.23

### PR DESCRIPTION
**Pull request by damemi**
In preparation for the 1.23 release, bumping to the 1.23 release candidate for soak time

ref https://github.com/kubernetes-sigs/descheduler/issues/641

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @ingvagabund 
helm test is failing, but it's not clear to me why. Maybe @stevehipwell could look too?

**Comment by stevehipwell** [comment]
@damemi haven't PSPs been removed in K8s v1.23?

**Comment by seanmalloy** [comment]
> @damemi haven't PSPs been removed in K8s v1.23?

If I recall correctly they are still deprecated. They will be removed in v1.25.

**Comment by seanmalloy** [comment]
> > @damemi haven't PSPs been removed in K8s v1.23?
> 
> If I recall correctly they are still deprecated. They will be removed in v1.25.

https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

**Comment by stevehipwell** [comment]
Thanks @seanmalloy, that would have been too easy.

@damemi are there any API version overrides in the values being used? Maybe for the cronjob? I'm not in front of my computer, so just guessing but might be able to take a proper look tomorrow.

**Comment by damemi** [comment]
@stevehipwell oh yeah! probably https://github.com/kubernetes-sigs/descheduler/pull/577

**Comment by damemi** [comment]
Hm, actually looks like we should still be good with v1beta1 until 1.25 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
/retest
maybe it's just a flake?

**Comment by damemi** [comment]
Now that 1.23 has released, I'm just updating this to use the GA tag. Still need to sort out why Helm test is failing, we have some ideas above.

In the meantime, we also need to make the regular updates to test-infra to run against k8s 1.23 and add a test for the release-1.23 branch. If there are any volunteers to make that change please feel free!

**Comment by damemi** [comment]
Ran this locally and saw this error in the pod logs:
```
$ kubectl logs pod/descheduler-ci-27319252-5lpdg -n kube-system
Error: unknown flag: --v
```

which looks like we need the change to initialize klog, similar to [this](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/581/commits/c339a947622142be4e6e0df7799cb2a1445e1eb2). I'll add that and report back

**Comment by damemi** [comment]
Green now, so this should be ready to merge

**Comment by ingvagabund** [comment]
Running locally with `-v=4` I don't see the descheduler logs

**Comment by damemi** [comment]
> Running locally with `-v=4` I don't see the descheduler logs

well that's not good...
/hold

**Comment by ingvagabund** [comment]
Klog seems to work, it's just the `--v` option that's not properly wired to it probably

**Comment by ingvagabund** [comment]
Because https://github.com/kubernetes/kubernetes/pull/106090

**Comment by damemi** [comment]
Thanks again @ingvagabund for solving that problem!

**Pull request merged**
