### PR TITLE
bump to k8s 1.26

### PR DESCRIPTION
**Pull request by JaneLiuL**
as title and issue https://github.com/kubernetes-sigs/descheduler/issues/1013

### CODE REVIEW

**Review by damemi — APPROVED** [review]
/approve
thanks @JaneLiuL !

**Comment by a7i** [comment]
@JaneLiuL Created the Issue and updated the Project board accordingly: https://github.com/orgs/kubernetes-sigs/projects/22/views/1

**Comment by damemi** [comment]
@a7i was there anything else holding this or good to merge?

**Comment by a7i** [comment]
@damemi I am trying to fix the build timeout issue before we merge any additional PR. The last push failed

**Comment by JaneLiuL** [comment]
so can be merge this first?   @damemi

**Comment by damemi** [comment]
@JaneLiuL not yet, let's merge https://github.com/kubernetes-sigs/descheduler/pull/1019 first (and some other less critical PRs) to make sure the builds aren't timing out any more before we merge this. Want to make sure the GA bump lands smoothly and builds

**Comment by JaneLiuL** [comment]
ok, i check https://github.com/kubernetes-sigs/descheduler/pull/1019 already merge done.

**Comment by damemi** [comment]
@JaneLiuL yeah, unfortunately it didn't fix the problem like we expected (see https://github.com/kubernetes-sigs/descheduler/pull/1023). This is why we want to find a fix first, then merge some other PRs before this one to test that the fix works.

We'll merge this as soon as we're sure we can get our builds to complete

**Comment by a7i** [comment]
@damemi and @JaneLiuL Given that we are temporarily unblocked (given the increased timeout), I'm going to /unhold this PR.

**Pull request merged**
