### PR TITLE
bump to k8s 1.27

### LINKED ISSUE #1078: Bump Kubernetes dependencies to v1.27.0 GA tags

### PR DESCRIPTION
**Pull request by a7i**
Closes #1078 

Related test-infra PR https://github.com/kubernetes/test-infra/pull/29285

### CODE REVIEW

**Comment by a7i** [comment]
tide/merge-method-squash

**Comment by ingvagabund** [comment]
Running `go mod tidy` and `go mod vendor` locally does not bring any new changes. +1 for rebasing with rcs.

**Review by damemi — COMMENTED** [review]
/approve

**Pull request merged**
