### PR TITLE
avoid redundant type conversion of DefaultEvictorArgs parameter in DefaultEvictor

### PR DESCRIPTION
**Pull request by fanhaouu**
Now the DefaultEvictorArgs parameters undergo redundant type conversion in DefaultEvictor, which is unnecessary.

This pr can resolve that.

### CODE REVIEW

**Review by a7i — APPROVED** [review]
/lgtm

Matches other plugins. Copied Jan for a final review to ensure it aligns with the future direction of plugins.

**Comment by ingvagabund** [comment]
All good here :) Thx

**Pull request merged**
