### PR TITLE
add fanhaouu to reviewers

### PR DESCRIPTION
**Pull request by fanhaouu**

### CODE REVIEW

**Comment by fanhaouu** [comment]
I'm not sure if what I'm doing conforms to the standards. 😊

**Comment by damemi** [comment]
Hi @fanhaouu, thank you for all of your contributions so far to the descheduler! It is fantastic that you are volunteering to help as a reviewer.

Unfortunately the [K8s community guidelines for reviewers](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer) require that you have been a member of the k8s org for at least 3 months and have reviewed/merged 20 PRs to be added as a reviewer. It looks like you were recently added to the k8s org, and you are still a little shy of having 20 PRs to the codebase. So I don't think we can approve this at this time, sorry.

Please do continue to contribute, as it is much appreciated! Feel free to reopen this in a few months. Thanks!

**Comment by fanhaouu** [comment]
> Hi @fanhaouu, thank you for all of your contributions so far to the descheduler! It is fantastic that you are volunteering to help as a reviewer.
> 
> Unfortunately the [K8s community guidelines for reviewers](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer) require that you have been a member of the k8s org for at least 3 months and have reviewed/merged 20 PRs to be added as a reviewer. It looks like you were recently added to the k8s org, and you are still a little shy of having 20 PRs to the codebase. So I don't think we can approve this at this time, sorry.
> 
> Please do continue to contribute, as it is much appreciated! Feel free to reopen this in a few months. Thanks!

Sorry, master, I didn't notice this rule. I'll continue contributing and meet the requirements as soon as possible.

**Pull request closed without merging**
