### PR TITLE
bump to kubernetes v0.32.0-rc.2

### PR DESCRIPTION
**Pull request by a7i**
in preparation for v0.32 release

Summary
The 1.32 release cycle is as follows:

Monday 9th September 2024: Week 1 — Release cycle begins
Thursday 3rd October 2024: Week 4 — [Production Readiness Freeze](https://groups.google.com/g/kubernetes-sig-architecture/c/a6_y81N49aQ)
02:00 UTC Friday 11th October 2024 / 19:00 PDT Thursday 10th October 2024: Week 5 — [Enhancements Freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#enhancements-freeze)
02:00 UTC Friday 8th November 2024 / 19:00 PDT Thursday 7th November 2024: Week 9 — [Code Freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#code-freeze) and [Test Freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#test-freeze)
Tuesday 12th - Friday 15th November 2024: Week 10 - [KubeCon NA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/)
Tuesday 26th November 2024: Week 12 — [Docs Freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#docs-freeze)
Tuesday 11th December 2024: Week 14 — Kubernetes v1.32.0 released

### CODE REVIEW

**Comment by seanmalloy** [comment]
golanglint-ci timed out in CI ...

```
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./_output/bin v1.62.2
golangci/golangci-lint info checking GitHub for tag 'v1.62.2'
golangci/golangci-lint info found version: 1.62.2 for v1.62.2/linux/amd64
golangci/golangci-lint info installed ./_output/bin/golangci-lint
./_output/bin/golangci-lint run
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
make: *** [Makefile:150: lint] Error 4
```

/retest

**Comment by seanmalloy** [comment]
Per the docs the default timeout for golangci-lint is one minute, https://golangci-lint.run/usage/configuration/. We should bump this up.

**Comment by seanmalloy** [comment]
@a7i we now have a real error in CI. See below.

```
./hack/verify-docs.sh
Generated output differs:
diff -Naupr /home/prow/go/src/sigs.k8s.io/descheduler/hack/../docs/cli/descheduler.md /tmp/tmp.zNyUKu25Ap/descheduler.md
--- /home/prow/go/src/sigs.k8s.io/descheduler/hack/../docs/cli/descheduler.md	2024-12-06 18:33:00.624234637 +0000
+++ /tmp/tmp.zNyUKu25Ap/descheduler.md	2024-12-06 18:37:59.350387463 +0000
@@ -33,7 +33,7 @@ descheduler [flags]
       --leader-elect                             Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
       --leader-elect-lease-duration duration     The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled. (default 2m17s)
       --leader-elect-renew-deadline duration     The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than the lease duration. This is only applicable if leader election is enabled. (default 1m47s)
-      --leader-elect-resource-lock string        The type of resource object that is used for locking during leader election. Supported options are 'leases', 'endpointsleases' and 'configmapsleases'. (default "leases")
+      --leader-elect-resource-lock string        The type of resource object that is used for locking during leader election. Supported options are 'leases'. (default "leases")
       --leader-elect-resource-name string        The name of resource object that is used for locking during leader election. (default "descheduler")
       --leader-elect-resource-namespace string   The namespace of resource object that is used for locking during leader election. (default "kube-system")
       --leader-elect-retry-period duration       The duration the clients should wait between attempting acquisition and renewal of a leadership. This is only applicable if leader election is enabled. (default 26s)
Generated conversions verify failed. Please run ./hack/update-docs.sh
make: *** [Makefile:145: verify-gen] Error 1

```

I'll submit a separate PR to bump the golangci-lint timeout to something more than 1 minute.

**Comment by a7i** [comment]
> @a7i we now have a real error in CI. See below.
> 
> ```
> ./hack/verify-docs.sh
> Generated output differs:
> diff -Naupr /home/prow/go/src/sigs.k8s.io/descheduler/hack/../docs/cli/descheduler.md /tmp/tmp.zNyUKu25Ap/descheduler.md
> --- /home/prow/go/src/sigs.k8s.io/descheduler/hack/../docs/cli/descheduler.md	2024-12-06 18:33:00.624234637 +0000
> +++ /tmp/tmp.zNyUKu25Ap/descheduler.md	2024-12-06 18:37:59.350387463 +0000
> @@ -33,7 +33,7 @@ descheduler [flags]
>        --leader-elect                             Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
>        --leader-elect-lease-duration duration     The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled. (default 2m17s)
>        --leader-elect-renew-deadline duration     The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than the lease duration. This is only applicable if leader election is enabled. (default 1m47s)
> -      --leader-elect-resource-lock string        The type of resource object that is used for locking during leader election. Supported options are 'leases', 'endpointsleases' and 'configmapsleases'. (default "leases")
> +      --leader-elect-resource-lock string        The type of resource object that is used for locking during leader election. Supported options are 'leases'. (default "leases")
>        --leader-elect-resource-name string        The name of resource object that is used for locking during leader election. (default "descheduler")
>        --leader-elect-resource-namespace string   The namespace of resource object that is used for locking during leader election. (default "kube-system")
>        --leader-elect-retry-period duration       The duration the clients should wait between attempting acquisition and renewal of a leadership. This is only applicable if leader election is enabled. (default 26s)
> Generated conversions verify failed. Please run ./hack/update-docs.sh
> make: *** [Makefile:145: verify-gen] Error 1
> ```
> 
> I'll submit a separate PR to bump the golangci-lint timeout to something more than 1 minute.

ah I think you!

**Comment by seanmalloy** [comment]
CI job pull-descheduler-verify-master has been running for a long time now, and seems to be stuck on golangci-lint. I'll submit a separate PR to add the `-v` flag for golangci-lint, so that we can hopefully debug the various timeout issues better in the future.

image

**Comment by a7i** [comment]
alright, let me do a force push to re-trigger it

**Pull request merged**
