### PR TITLE
use v1alpha2 api for helm chart default values

### PR DESCRIPTION
**Pull request by a7i**
I assume this needs a chart bump?

### CODE REVIEW

**Comment by a7i** [comment]
@JaneLiuL would you please review?

**Comment by arthurk** [comment]
Same for me. I installed it yesterday and it works fine but there is big warning in the readme about v1 being deprecated and recommend switching to v2, yet the chart only works with v1.

**Comment by sherifabdlnaby** [comment]
Plus one here!

**Comment by a7i** [comment]
this was communicated by @knelasevero yesterday so we should be merging it soon

**Comment by a7i** [comment]
cc: @jklaw90

**Pull request merged**
