### PR TITLE
Update NOTES.txt

### PR DESCRIPTION
**Pull request by developer-guy**

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test

**Comment by developer-guy** [comment]
hello @damemi, looks like the failing tests are not related to us, would you mind verifying this? Thanks in advance 🙋🏻‍♂️

**Review by damemi — COMMENTED** [review]
@developer-guy yeah, I think that's a flake because we saw it in another PR. But since this does affect the helm chart I'd just like to see it pass before merging
/retest

**Pull request merged**
