### PR TITLE
Update Event Logging to Use Structured Logging

### PR DESCRIPTION
**Pull request by seanmalloy**
Related to #347.

### CODE REVIEW

**Comment by seanmalloy** [comment]
I confirmed it compiles, but did not test it yet.

/hold

**Comment by seanmalloy** [comment]
Confirmed working. The logs created by `event.go` are now structured logs. These logs only get printed at log level greater than or equal to 3.

```
./_output/bin/descheduler --kubeconfig=/Users/myuser/.kube/config --policy-config-file=./examples/pod-life-time.yml --v=3
I1001 00:57:27.950065   50322 node.go:46] "Node lister returned empty list, now fetch directly"
I1001 00:57:28.080233   50322 pod_lifetime.go:92] "Processing node" node="master-a"
I1001 00:57:28.174701   50322 pod_lifetime.go:92] "Processing node" node="master-b"
I1001 00:57:28.335082   50322 evictions.go:117] "Evicted pod" pod="openshift-config-operator/openshift-config-operator-7c86496786-qf2vl" reason=" (PodLifeTime)"
I1001 00:57:28.335369   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-config-operator/openshift-config-operator-7c86496786-qf2vl" maxPodLifeTime=60
I1001 00:57:28.335394   50322 pod_lifetime.go:92] "Processing node" node="master-c"
I1001 00:57:28.335656   50322 event.go:291] "Event occurred" object="openshift-config-operator/openshift-config-operator-7c86496786-qf2vl" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.431837   50322 pod_lifetime.go:92] "Processing node" node="router-a-7j2jk"
I1001 00:57:28.569738   50322 evictions.go:117] "Evicted pod" pod="openshift-console/downloads-97db85755-6wmb6" reason=" (PodLifeTime)"
I1001 00:57:28.569985   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-console/downloads-97db85755-6wmb6" maxPodLifeTime=60
I1001 00:57:28.570226   50322 event.go:291] "Event occurred" object="openshift-console/downloads-97db85755-6wmb6" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.657059   50322 evictions.go:117] "Evicted pod" pod="openshift-kube-storage-version-migrator/migrator-84f6d56959-lnw68" reason=" (PodLifeTime)"
I1001 00:57:28.657298   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-kube-storage-version-migrator/migrator-84f6d56959-lnw68" maxPodLifeTime=60
I1001 00:57:28.657399   50322 event.go:291] "Event occurred" object="openshift-kube-storage-version-migrator/migrator-84f6d56959-lnw68" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.723524   50322 evictions.go:117] "Evicted pod" pod="openshift-marketplace/certified-operators-ff5f5d7f5-gx888" reason=" (PodLifeTime)"
I1001 00:57:28.723692   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-marketplace/certified-operators-ff5f5d7f5-gx888" maxPodLifeTime=60
I1001 00:57:28.723825   50322 event.go:291] "Event occurred" object="openshift-marketplace/certified-operators-ff5f5d7f5-gx888" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.799006   50322 evictions.go:117] "Evicted pod" pod="openshift-marketplace/community-operators-7cdb87cbc5-k7whg" reason=" (PodLifeTime)"
I1001 00:57:28.799211   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-marketplace/community-operators-7cdb87cbc5-k7whg" maxPodLifeTime=60
I1001 00:57:28.799404   50322 event.go:291] "Event occurred" object="openshift-marketplace/community-operators-7cdb87cbc5-k7whg" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.864123   50322 evictions.go:117] "Evicted pod" pod="openshift-marketplace/redhat-marketplace-6b75b995f5-2np5r" reason=" (PodLifeTime)"
I1001 00:57:28.864348   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-marketplace/redhat-marketplace-6b75b995f5-2np5r" maxPodLifeTime=60
I1001 00:57:28.864450   50322 event.go:291] "Event occurred" object="openshift-marketplace/redhat-marketplace-6b75b995f5-2np5r" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:28.954734   50322 evictions.go:117] "Evicted pod" pod="openshift-marketplace/redhat-operators-8479cd5684-ct8zr" reason=" (PodLifeTime)"
I1001 00:57:28.954849   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-marketplace/redhat-operators-8479cd5684-ct8zr" maxPodLifeTime=60
I1001 00:57:28.954870   50322 pod_lifetime.go:92] "Processing node" node="router-a-tsvp4"
I1001 00:57:28.954900   50322 event.go:291] "Event occurred" object="openshift-marketplace/redhat-operators-8479cd5684-ct8zr" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:29.153786   50322 evictions.go:117] "Evicted pod" pod="xpaas-operations/k-rhel7-diags-6b8db8bc86-wxt8k" reason=" (PodLifeTime)"
I1001 00:57:29.153973   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="xpaas-operations/k-rhel7-diags-6b8db8bc86-wxt8k" maxPodLifeTime=60
I1001 00:57:29.154057   50322 pod_lifetime.go:92] "Processing node" node="router-b-7qrsg"
I1001 00:57:29.154057   50322 event.go:291] "Event occurred" object="xpaas-operations/k-rhel7-diags-6b8db8bc86-wxt8k" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
I1001 00:57:29.312228   50322 evictions.go:117] "Evicted pod" pod="openshift-console/downloads-97db85755-cwmgz" reason=" (PodLifeTime)"
I1001 00:57:29.312379   50322 pod_lifetime.go:98] "Evicted pod because it exceeded its lifetime" pod="openshift-console/downloads-97db85755-cwmgz" maxPodLifeTime=60
I1001 00:57:29.312414   50322 pod_lifetime.go:92] "Processing node" node="router-f-qn594"
I1001 00:57:29.312539   50322 event.go:291] "Event occurred" object="openshift-console/downloads-97db85755-cwmgz" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/descheduler (PodLifeTime)"
```

/hold cancel
/assign @damemi 
/cc @ingvagabund @lixiang233

**Review by damemi — APPROVED** [review]
/approve

**Pull request merged**
