### PR TITLE
use pod informers for listing pods in removepodsviolatingtopologyspreadconstraint and removepodsviolatinginterpodantiaffinity

### PR DESCRIPTION
**Pull request by a7i**
follow up to #1033 and apply the same in removepodsviolatingtopologyspreadconstraint

### CODE REVIEW

**Comment by a7i** [comment]
With informers, the returned pods are not in order so the assertion is failing. Any suggestions @knelasevero @ingvagabund ?

e.g. one of the tests is expecting this order:
```
expectedEvictedPods:  []string{"pod-5", "pod-6", "pod-7", "pod-8"},
```

**Comment by damemi** [comment]
> With informers, the returned pods are not in order so the assertion is failing. Any suggestions @knelasevero @ingvagabund ?
> 
> e.g. one of the tests is expecting this order:
> 
> ```
> expectedEvictedPods:  []string{"pod-5", "pod-6", "pod-7", "pod-8"},
> ```

I haven't looked at the test, but is there anything semantically different about evicting those different pods? If it's just an ordering issue then you can sort or update the output

**Comment by ingvagabund** [comment]
Tests should not assume a list of pods will always be returned in the same order as inserted. It just happened to be the case :) Sorting the list wherever it makes sense is fine.

**Comment by ingvagabund** [comment]
```
topologyspreadconstraint_test.go:1220: Expected pods [pod-5 pod-6 pod-7 pod-8] to be evicted but [pod-8 pod-5 pod-6 pod-7] were not evicted. Actual pods evicted: [pod-1 pod-2 pod-3 pod-10 pod-11]
```

The test is probably broken. `expectedEvictedCount` is 5 but the list claims it needs only 4 items.

**Comment by a7i** [comment]
> ```
> topologyspreadconstraint_test.go:1220: Expected pods [pod-5 pod-6 pod-7 pod-8] to be evicted but [pod-8 pod-5 pod-6 pod-7] were not evicted. Actual pods evicted: [pod-1 pod-2 pod-3 pod-10 pod-11]
> ```
> 
> The test is probably broken. `expectedEvictedCount` is 5 but the list claims it needs only 4 items. We should probably randomize the order in which the pods are appended into `objs` var that is passed into `fake.NewSimpleClientset` in cases where the order does not matter. At the same time I recall we needed some tests to actually evict a specific list of pods so we can validate the code picks the right pods for eviction.

Thanks @ingvagabund . The test only checks that expected is included in the evicted list, so having only 4 was passing before.

Yes, there are ~3 tests that are expecting a particular order. I can perhaps change them to evicted count per node/topology.

**Comment by a7i** [comment]
fyi - it used to be sored, but then it changed: https://github.com/kubernetes/kubernetes/pull/75730
> "noone should assume the fact that keys are sorted."

**Pull request merged**
