### PR TITLE
feat: update to golang 1.22.7 | Fix critical vulnerabilities

### PR DESCRIPTION
**Pull request by sagar-18**

### CODE REVIEW

**Comment by a7i** [comment]
looks like it was missed in the initial PR: https://github.com/kubernetes-sigs/descheduler/pull/1539

we need to upgrade these first: https://github.com/a7i/test-infra/blob/master/config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml

**Comment by a7i** [comment]
@sagar-18 the PR you linked is for the release branch submits, we'll need to update master as well? https://github.com/sagar-18/test-infra/blob/master/config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml

**Comment by sagar-18** [comment]
> @sagar-18 the PR you linked is for the release branch submits, we'll need to update master as well? https://github.com/sagar-18/test-infra/blob/master/config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml

@a7i for the master branch, we have to use the 1.23 golang version, as 1.22 is going to be EOL after 3 months.

**Comment by sagar-18** [comment]
> @sagar-18: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-descheduler-verify-release-1-30	[0424cf4](https://github.com/kubernetes-sigs/descheduler/commit/0424cf44dda4cd69d56cfd8d93ae4ed942158fad)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_descheduler/1550/pull-descheduler-verify-release-1-30/1857062968605282304)	true	`/test pull-descheduler-verify-release-1-30`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=descheduler&pr=1550). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Asagar-18). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/descheduler/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

@a7i @ingvagabund, now this one is failing. pls guide

**Comment by sagar-18** [comment]
@a7i pls comment

**Pull request merged**
