### PR TITLE
Fix values.yml

### PR DESCRIPTION
**Pull request by rabbagliettiandrea**
Add RemovePodsViolatingTopologySpreadConstraint to values.yml

### CODE REVIEW

**Comment by a7i** [comment]
Can the commit message be changed to something along these lines:

include RemovePodsViolatingTopologySpreadConstraint in DeschedulerPolicy for helm chart

**Review by damemi — COMMENTED** [review]
/ok-to-test
/approve

**Comment by ingvagabund** [comment]
Hello @rabbagliettiandrea, thank You for extending the list of strategies in the helm chart. Have you had a chance to setup your CLA?

**Comment by seanmalloy** [comment]
@[rabbagliettiandrea] any luck getting the CLA signed? Do you need any assistance with the CLA?

**Comment by rabbagliettiandrea** [comment]
Hi Sean :)
frankly speaking, I'm not very confident to signup a contract that I can barely understand just to do a PR.
At the same time, I'm very up to contribute to OSS world.

Thank you for your awesome work guys,
Andrea

**Comment by knelasevero** [comment]
I think we can close this one. Contributor is not willing to sign CLA, and also those files will be different when the new changes for v1alpha2 hit the repo

**Comment by knelasevero** [comment]
Will close, but anyone that thinks this should be reopened, feel free to reopen :D

/close

**Pull request closed without merging**
