### PR TITLE
Update Docs and Manifests for v0.21.0

### PR DESCRIPTION
**Pull request by seanmalloy**
* Added v0.21 references to README
* Update k8s manifests with v0.21.0 references
* Added table with list of supported architectures by release

### CODE REVIEW

**Comment by seanmalloy** [comment]
Getting close to the v0.21.0 release.

/kind documentation
/hold

**Review by damemi — COMMENTED** [review]
/lgtm
feel free to release the hold after we publish the release

**Comment by seanmalloy** [comment]
> /lgtm
> feel free to release the hold after we publish the release

@damemi if we don't merge the changes to the k8s YAML manifests before the release is published then the kustomize install instructions will not work as expected. Running the below command will install descheduler v0.20.0.
```
kustomize build 'github.com/kubernetes-sigs/descheduler/kubernetes/job?ref=v0.21.0' | kubectl apply -f -
```

**Comment by damemi** [comment]
@seanmalloy fair enough, I wasn't sure if you wanted to merge the changes for installing v0.21 before that tag had been published. But since this is the master branch, and the release is going to follow soon after, I think it's fine
/hold cancel

**Pull request merged**
