### PR TITLE
Add MinNoOfPodsToEvictForReplicas

### PR DESCRIPTION
**Pull request by jiangxiaobin96**
Fix issue: #786

### CODE REVIEW

**Comment by jiangxiaobin96** [comment]
same as issue [#658](https://github.com/kubernetes-sigs/descheduler/pull/658)

**Review by damemi — COMMENTED** [review]
/ok-to-test

**Review by a7i — COMMENTED** [review]
Isn't it better for the workload itself to define a `PodDisruptionBudget` to handle `maxUnavailable` or `minAvailable`?

**Comment by jiangxiaobin96** [comment]
> Isn't it better for the workload itself to define a `PodDisruptionBudget` to handle `maxUnavailable` or `minAvailable`?

Yes, if deploying  `PodDisruptionBudget`,  Disruption Budget will be better.

**Comment by jiangxiaobin96** [comment]
`PodDisruptionBudget ` is better if deployed in user mode.

**Pull request closed without merging**
