### PR TITLE
Update e2e tests to use kind v0.9.0

### PR DESCRIPTION
**Pull request by seanmalloy**

### CODE REVIEW

**Comment by seanmalloy** [comment]
/assign @damemi @ingvagabund 

I also submitted https://github.com/kubernetes/test-infra/pull/19221 to bump the k8s versions being used for e2e tests.

**Comment by seanmalloy** [comment]
@damemi I think you might need to mark `pull-descheduler-test-e2e-k8s-master-1-19` as required in branch protection settings and remove `pull-descheduler-test-e2e-k8s-master-1-16`.

**Review by damemi — APPROVED** [review]
/approve
@seanmalloy I think the required tests/branch protection are managed by the config in k8s/test-infra

**Pull request merged**
