### PR TITLE
Update Docs and Manifests for v0.24.0

### PR DESCRIPTION
**Pull request by pravarag**
Changes covered as part of this PR are:

- [ ] Added v0.24 references to README
- [ ]  Update k8s manifests with v0.24.0 references
- [ ] Added table with list of supported architectures by release

### CODE REVIEW

**Comment by damemi** [comment]
@pravarag looks like there may be some different issue in the 1.24 test (not related to this PR), do you have a moment to look into that?

**Comment by pravarag** [comment]
> @pravarag looks like there may be some different issue in the 1.24 test (not related to this PR), do you have a moment to look into that?

I can see following error being reported in prow job logs:
```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```
I'll just check whether it's actually failing on this step or not.

**Review by damemi — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
