### PR TITLE
Remove k8s.io/kubernetes deps and switch to go modules

### PR DESCRIPTION
**Pull request by damemi**
The ultimate goal of this PR is to switch to go modules. The easiest way to do that is to break our dependency on `k8s.io/kubernetes`. A lot of our usage of it is relatively simple helper methods and constants that can be easily copied to our own `utils` package, or variables that are available in external apis anyway.

Fixes https://github.com/kubernetes-sigs/descheduler/issues/207, https://github.com/kubernetes-sigs/descheduler/issues/200

### CODE REVIEW

**Comment by damemi** [comment]
/cc @aveshagarwal this is what I'm thinking. It's an annoying number of helper funcs that need to just be copied over, but maybe we could just refactor their usage out anyway.

/hold
for review

**Comment by damemi** [comment]
/hold cancel
Looks like this builds and passes unit tests now

**Comment by damemi** [comment]
@aveshagarwal do you have any feedback you could provide for this? It cuts down our vendored dependencies significantly, for adding only a few hundred lines of copied util functions

**Comment by aveshagarwal** [comment]
> @aveshagarwal do you have any feedback you could provide for this? It cuts down our vendored dependencies significantly, for adding only a few hundred lines of copied util functions

I will review it soon.

**Comment by aveshagarwal** [comment]
@damemi have you run "go mod tidy"?

**Comment by damemi** [comment]
>@damemi have you run "go mod tidy"?

@aveshagarwal yes, and I just ran it again to double check after rebasing on master. No changes

**Comment by ravisantoshgudimetla** [comment]
/approve

@aveshagarwal - Please unhold once you're fine with the changes.

**Pull request merged**
