### PR TITLE
Add default logging-format value

### PR DESCRIPTION
**Pull request by damemi**
Fixes https://github.com/kubernetes-sigs/descheduler/issues/487
/kind bug

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/hold
still need to test

**Comment by eatwithforks** [comment]
Hi, thanks for the fix! do you plan to cut a new release with this fix? 

i've tried adding ./descheduler --logging-format json to v0.2.0 but i'm still seeing 
```
"failed to validate server configuration\" err=\"unsupported log format: \""
```

**Comment by damemi** [comment]
Yes, this will be included in v0.21 which will be cut and published in a few weeks

**Pull request merged**
