### PR TITLE
Start using kind for e2e tests

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
First pass to start using `kind` for tests.

/cc @aveshagarwal @sjenning

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
I can see that tests are passing. The only thing that I am not sure about is - Are evictions happening for sure or lownodeutilization strategy is not doing anything because of the thresholds. Will verify this and get back in a day or 2.

@aveshagarwal - This can be reviewed :).

**Comment by aveshagarwal** [comment]
> I can see that tests are passing. The only thing that I am not sure about is - Are evictions happening for sure or lownodeutilization strategy is not doing anything because of the thresholds. Will verify this and get back in a day or 2.

thanks for this PR. it LGTM. Let me know when you are done with verification and then we can merge it.

**Comment by ravisantoshgudimetla** [comment]
Tested this locally. Working fine...

**Comment by ravisantoshgudimetla** [comment]
@aveshagarwal - Need your lgtm and approval

**Pull request closed without merging**
