### PR TITLE
Use correct GCR staging registry

### PR DESCRIPTION
**Pull request by seanmalloy**
The container registry now defaults to the correct staging registry.

### CODE REVIEW

**Comment by seanmalloy** [comment]
@ravisantoshgudimetla and @aveshagarwal would you be able to confirm that you can successfully push to the staging registry?

**Comment by aveshagarwal** [comment]
@seanmalloy  thanks for your effort on this. I will try to do it soon. or if you could tell me steps i should follow, i could try faster.

**Comment by seanmalloy** [comment]
@aveshagarwal please try these steps ...

Install the Google Cloud CLI(gcloud) ... https://cloud.google.com/sdk/install.

Build and push an image to Google Container Registry ...
```
$ make image
$ make push
```

Assuming this all works then you should be able to use the `gcloud` command to list the images in the Google Container Registry. The GCP project name is `k8s-staging-descheduler`.

```
$ gcloud container images list --repository gcr.io/k8s-staging-descheduler
```

Or you could view the Google Container Registry for GCP project `k8s-staging-descheduler` in your web browser using the below URL.

https://console.cloud.google.com/gcr/images/k8s-staging-descheduler?project=k8s-staging-descheduler

**Comment by ravisantoshgudimetla** [comment]
Thanks for working on this @seanmalloy.


I tried this today and I got the following error:

`denied: Token exchange failed for project 'k8s-image-staging'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
make: *** [Makefile:51: push-container-to-gcloud] Error 1
`

**Comment by seanmalloy** [comment]
I have verified I can override the `REGISTRY` variable and push to my own private GCR registry.

```
REGISTRY=us.gcr.io/my-gcp-project make push
docker build -t descheduler:`git describe --tags` .
Sending build context to Docker daemon  386.1MB
Step 1/8 : FROM golang:1.12.12
 ---> 25f57e47afce
Step 2/8 : WORKDIR /go/src/sigs.k8s.io/descheduler
 ---> Using cache
 ---> 6e66b8fbf3b1
Step 3/8 : COPY . .
 ---> Using cache
 ---> 47c370a73d34
Step 4/8 : RUN make
 ---> Using cache
 ---> a3a0cc9e0a01
Step 5/8 : FROM scratch
 --->
Step 6/8 : MAINTAINER Avesh Agarwal <avagarwa@redhat.com>
 ---> Using cache
 ---> dacd7bd6116e
Step 7/8 : COPY --from=0 /go/src/sigs.k8s.io/descheduler/_output/bin/descheduler /bin/descheduler
 ---> Using cache
 ---> ceb00f462df1
Step 8/8 : CMD ["/bin/descheduler", "--help"]
 ---> Using cache
 ---> b35736aaf8ab
Successfully built b35736aaf8ab
Successfully tagged descheduler:0.9.0-49-g22f9aa53
gcloud auth configure-docker
gcloud credential helpers already registered correctly.
...
docker tag descheduler:`git describe --tags` us.gcr.io/my-gcp-project/descheduler:`git describe --tags`
docker push us.gcr.io/my-gcp-project/descheduler:`git describe --tags`
The push refers to repository [us.gcr.io/my-gcp-project/descheduler]
3fa12146aa11: Pushed
0.9.0-49-g22f9aa53: digest: sha256:ee917f51335731e7fe9ac629f265d2a2ae0c903fc30d124d02afa12cd470c7ae size: 529
```

So ...

I believe I have the correct staging GCR repo set in the Makefile. For reference all of the GCR registry access was setup in kubernetes/k8s.io/pull/296.

Or maybe there is some different process for pushing to the staging GCR repo? Or people do not get direct push access to the staging repo?

I will try to follow up with the SIG that is responsible for the setting up the GCR registries to see what I may have missed. Beyond that I'm not sure what else I can do because I don't have access to push to the staging registry.

**Comment by seanmalloy** [comment]
@aveshagarwal would you be able to test this to see if it works for you? I'm not sure why @ravisantoshgudimetla would not have permissions to push to the staging registry. Please use your Google account associated with your email address listed [here](https://github.com/kubernetes/k8s.io/blob/f7715c03741b081abacc78e651d1d1702bdd8c42/groups/groups.yaml#L573).

**Comment by seanmalloy** [comment]
@aveshagarwal and @ravisantoshgudimetla would one of you have some time to test this in the near-ish future? Would be great if you could confirm if the GCP permissions are working or not. Just make sure you are using your emails listed [here](https://github.com/kubernetes/k8s.io/blob/f7715c03741b081abacc78e651d1d1702bdd8c42/groups/groups.yaml#L573) for gcloud authentication.

I realize it is very possible that you might not have time to test this out, so in that case is there another person from SIG scheduling that we could give access to for testing? I'd be more than happy submit the PR to get another person access.

**Comment by seanmalloy** [comment]
I got confirmation in `#sig-scheduling` on Slack that @damemi is being given access to push to gcr.io/k8s-staging-descheduler. See pull request https://github.com/kubernetes/k8s.io/pull/537. Once that PR is merge then @damemi will have access to test the push to the staging container registry.

**Comment by seanmalloy** [comment]
@damemi pull request https://github.com/kubernetes/k8s.io/pull/537 is merged now, so you should be able to test this now. I can reach out to [k8s Infra working group](https://github.com/kubernetes/community/tree/master/wg-k8s-infra) if it still does not work.

**Comment by damemi** [comment]
@seanmalloy I have successfully pushed the image to the gcr.io registry:
```
$ gcloud container images list --repository gcr.io/k8s-staging-descheduler
NAME
gcr.io/k8s-staging-descheduler/descheduler
```

However while doing so I noticed some bugs in the Makefile that prevented the image from being properly tagged. It's 3 lines, here: https://github.com/damemi/descheduler/commit/9243720cb540d212e97f903daaf9ac8f3c9560a0#diff-b67911656ef5d18c4ae36cb6741b7965R18-R20. Do you want to pull those changes into this PR, and I will /lgtm?

**Comment by seanmalloy** [comment]
@damemi I incorporated your changes to the Makefile. See commit 361aa01c5196c947cb7d73c80fe7c53c3c612b1e.

**Comment by damemi** [comment]
@seanmalloy awesome, sorry for the delay on getting this pushed.
/lgtm

**Comment by damemi** [comment]
@aveshagarwal can you approve?

**Comment by aveshagarwal** [comment]
thanks @seanmalloy and @damemi for working on this.

**Pull request merged**
