### PR TITLE
fix default value assignment of EvictLocalStoragePods

### PR DESCRIPTION
**Pull request by a7i**
Patching 0.26 (0.26.1)
https://github.com/kubernetes-sigs/descheduler/pull/1104#issuecomment-1493447747

### CODE REVIEW

**Comment by damemi** [comment]
@a7i should I push a v0.26.1 tag to the release branch so we can start the patch release process?

**Comment by a7i** [comment]
@damemi yes, please. how do I go about getting permission to create tags?

**Comment by damemi** [comment]
@a7i I think we update https://github.com/kubernetes/org/blob/b7bd5eb8af25bd3c5917bf5ecee720e84ee7095b/config/kubernetes-sigs/sig-scheduling/teams.yaml#L20-L28

We should really work on a way to automate our release flow instead of having one person manually push a tag right to remote (😬). Something like an issue or PR merge that requires at least a second person to lgtm/approve would be cool. For me, this tag push is the most stressful part of each release because I worry about messing it up.  We could probably set up a github action to do that.

For now, v0.26.1 is pushed

**Pull request merged**
