### PR TITLE
docs: adding clarification to HighNodeUtilization's purpose

### PR DESCRIPTION
**Pull request by chrisjohnson00**
This PR resolves issue #591

### CODE REVIEW

**Comment by chrisjohnson00** [comment]
I've signed the CLA

**Review by ingvagabund — CHANGES_REQUESTED** [review]

**Review by damemi — COMMENTED** [review]
/ok-to-test
/approve
thanks @chrisjohnson00, after @ingvagabund's comment I think this helps.

You'll also need to sign the CLA before this will merge. Thanks again!

**Comment by chrisjohnson00** [comment]
> You'll also need to sign the CLA before this will merge. Thanks again!

I signed it yesterday, but `/check-cla` doesn't seem to be clearing the check... what can I do here?

**Comment by damemi** [comment]
That's odd, usually it should pick it up pretty quick. Maybe the bot is just delayed right now for some reason, if it doesn't update we can look into it

**Comment by damemi** [comment]
@chrisjohnson00 I'm not sure why the CLA check isn't passing for you, perhaps you could try filling it out again? You could also ask in #sig-contribex on k8s slack and they should be able to help

**Comment by chrisjohnson00** [comment]
Woohoo!!

**Pull request merged**
