### PR TITLE
Add k8s events support

### LINKED ISSUE #166: Emit k8s Event When a Pod Is Evicted
It would be useful if the descheduler emitted a k8s event when it successfully evicts a pod. The event should be created in same namespace as the evicted pod.

### PR DESCRIPTION
**Pull request by seanmalloy**
ecc4be572f4e3e7cfdfe45f34552135483f89587 - add support for k8s events
1793de2c34a970c8d3f7cc3673381418ac47d430 - vendor package github.com/golang/groupcache/lru

### CODE REVIEW

**Comment by seanmalloy** [comment]
it compiles now, but I have not tested the code.

**Comment by seanmalloy** [comment]
I think I want to wait until #188 is merged, so that the newer v1 Event API can be used instead of v1beta1.

**Comment by damemi** [comment]
This looks good to me, and I've updated #188 which can hopefully merge soon

**Comment by damemi** [comment]
@seanmalloy #188 has merged now, so you should be able to use the new event api

**Comment by seanmalloy** [comment]
/assign @damemi 

I updated the code to use the v1 Event API. I believe this PR is ready for review now. I have successfully tested this code against OpenShift v3.11 to confirm that k8s events are successfully created. See below screenshot from the OpenShift web UI that shows the successfully created events.

Screen Shot 2019-11-15 at 10 20 32 PM

**IMPORTANT NOTE:** I was not able to successfully add a new package to the `vendor` directory using `glide`. See the commit message for commit 1793de2 for additional details. @mcandre and I tried several different `glide` commands, but every attempt resulted in a compile error. See also #198.

**Comment by damemi** [comment]
@seanmalloy thanks, I'll review this but it's interesting that glide wouldn't add that dependency for you, I would think that `glide up` should do it. I do see that that is the first commit though, which could be the problem. Glide looks for dependencies in the code to automatically add them, so I'm not sure how to manually add one without the code being there. I would recommend trying to reset your 2 commits, cherry-pick the actual change, then run `glide up -v`

**Comment by damemi** [comment]
@seanmalloy have you had a chance to try what I suggested? Your PR looks good but we shouldn't attempt to manually add dependencies to the vendor directory. I've tried the following commands locally on your branch which compiled for me, if you run them and push back to your branch it should be in an approve-able state:

```
$ git reset --hard HEAD~2
$ git cherry-pick ecc4be572f4e3e7cfdfe45f34552135483f89587
$ glide up -v
$ git commit.....(add your commit message)
```

**Comment by damemi** [comment]
/hold
for dep update

**Comment by seanmalloy** [comment]
@damemi I was able to update the dependencies in the `vendor` directory using your instructions. Thanks for the help!

e3d06d154140010b8473bead940669e874facdc4 - code changes to add event support
6654aeff997a428ea6b6fb583bf3aa255ab3e4d9 - vendor dependency updates using "glide up -v"

I confirmed that the code compiles, and also ran the descheduler against an OpenShift v3.11 cluster. Everything is working fine from my perspective.

Let me know if any additional changes are needed.

**Comment by damemi** [comment]
@seanmalloy thanks for the update, glad I could help. Will need someone to approve this but I can lgtm

/lgtm

**Pull request merged**
