### PR TITLE
RemoveFailedPods: guard against nil descheduler strategy (e.g. in case of default that loads all strategies)

### LINKED ISSUE #630: Crash in RemoveFailedPods strategy
**What version of descheduler are you using?**

descheduler version: 0.22

**Please provide a copy of your descheduler policy config file**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveFailedPods":
        enabled: true
```
Disabling RemovedFailedPods I can run all other policies.

**What k8s version are you using (`kubectl version`)?**
1.22.1
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"archive", BuildDate:"2021-08-19T21:28:12Z", GoVersion:"go1.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

```
I0918 06:44:25.850399       1 named_certificates.go:53] "Loaded SNI cert" index=0 certName="self-signed loopback" certDetail="\"apiserver-loopback-client@1631947465\" [serving] validServingFor=[apiserver-loopback-client] issuer=\"apiserver-loopback-client-ca@1631947464\" (2021-09-18 05:44:23 +0000 UTC to 2022-09-18 05:44:23 +0000 UTC (now=2021-09-18 06:44:25.85028599 +0000 UTC))"
I0918 06:44:25.850606       1 secure_serving.go:195] Serving securely on [::]:10258
I0918 06:44:25.851136       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0918 06:44:25.895398       1 node.go:46] "Node lister returned empty list, now fetch directly"
E0918 06:44:25.919640       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14cdf80, 0x26e1770)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x84
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x80
panic(0x14cdf80, 0x26e1770)
	/usr/local/go/src/runtime/panic.go:965 +0x154
sigs.k8s.io/descheduler/pkg/descheduler/strategies.RemoveFailedPods(0x1a00468, 0x400019c020, 0x1a26ab8, 0x400002ac60, 0x4000255801, 0x0, 0x0, 0x4000602720, 0x6, 0x6, ...)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/failedpods.go:44 +0x70
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies.func1()
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:145 +0x26c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4000707ad0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000707ad0, 0x19c1ff0, 0x4000454210, 0x1, 0x4000028420)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000707ad0, 0x0, 0x0, 0x1, 0x4000028420)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies(0x1a00468, 0x400019c020, 0x400046c2c0, 0x40001a6140, 0x40003be487, 0x9, 0x4000028420, 0x4000092c00, 0x40000ee460)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:117 +0x534
sigs.k8s.io/descheduler/pkg/descheduler.Run(0x400046c2c0, 0x19c2050, 0x400021c0e0)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:64 +0x154
sigs.k8s.io/descheduler/cmd/descheduler/app.Run(...)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:93
sigs.k8s.io/descheduler/cmd/descheduler/app.NewDeschedulerCommand.func1(0x40003ba280, 0x400012b7c0, 0x0, 0x4)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:78 +0xb8
github.com/spf13/cobra.(*Command).execute(0x40003ba280, 0x40001a6010, 0x4, 0x4, 0x40003ba280, 0x40001a6010)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x40003ba280, 0x400063ff48, 0x1, 0x1)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/descheduler.go:34 +0xa0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12b7020]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x108
panic(0x14cdf80, 0x26e1770)
	/usr/local/go/src/runtime/panic.go:965 +0x154
sigs.k8s.io/descheduler/pkg/descheduler/strategies.RemoveFailedPods(0x1a00468, 0x400019c020, 0x1a26ab8, 0x400002ac60, 0x4000255801, 0x0, 0x0, 0x4000602720, 0x6, 0x6, ...)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/failedpods.go:44 +0x70
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies.func1()
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:145 +0x26c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4000707ad0)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x64
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000707ad0, 0x19c1ff0, 0x4000454210, 0x1, 0x4000028420)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x74
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000707ad0, 0x0, 0x0, 0x1, 0x4000028420)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
sigs.k8s.io/descheduler/pkg/descheduler.RunDeschedulerStrategies(0x1a00468, 0x400019c020, 0x400046c2c0, 0x40001a6140, 0x40003be487, 0x9, 0x4000028420, 0x4000092c00, 0x40000ee460)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:117 +0x534
sigs.k8s.io/descheduler/pkg/descheduler.Run(0x400046c2c0, 0x19c2050, 0x400021c0e0)
	/go/src/sigs.k8s.io/descheduler/pkg/descheduler/descheduler.go:64 +0x154
sigs.k8s.io/descheduler/cmd/descheduler/app.Run(...)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:93
sigs.k8s.io/descheduler/cmd/descheduler/app.NewDeschedulerCommand.func1(0x40003ba280, 0x400012b7c0, 0x0, 0x4)
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/app/server.go:78 +0xb8
github.com/spf13/cobra.(*Command).execute(0x40003ba280, 0x40001a6010, 0x4, 0x4, 0x40003ba280, 0x40001a6010)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x40003ba280, 0x400063ff48, 0x1, 0x1)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/sigs.k8s.io/descheduler/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/go/src/sigs.k8s.io/descheduler/cmd/descheduler/descheduler.go:34 +0xa0

```

### PR DESCRIPTION
**Pull request by a7i**
Closes #630 

Background: Descheduler by default loads all strategies and as a result, the strategy params can be nil. The strategy needs to guard against that.

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
The error reported came from line 44: `/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/failedpods.go:44 +0x70`

So, we also need to add a guard for the priority threshold to be non-nil https://github.com/kubernetes-sigs/descheduler/pull/632/files#diff-413def6475d16ce340793b62bb4c179595cc28669ad68d474763006464d8ee65R44

**Comment by damemi** [comment]
Also, would be good to add a test for this. It should probably be an e2e so that the whole config gets tested against (rather than just the eviction logic in a unit test)

**Comment by a7i** [comment]
> The error reported came from line 44: `/go/src/sigs.k8s.io/descheduler/pkg/descheduler/strategies/failedpods.go:44 +0x70`
> 
> So, we also need to add a guard for the priority threshold to be non-nil https://github.com/kubernetes-sigs/descheduler/pull/632/files#diff-413def6475d16ce340793b62bb4c179595cc28669ad68d474763006464d8ee65R44

Hey @damemi thresholdPriority blongs to `ValidatedStrategyParams` so this is the actual fix:
```
-	*validation.ValidatedStrategyParams
+	validation.ValidatedStrategyParams
```

I have added a unit test which will catch the error if reverted back to reference.

**Comment by damemi** [comment]
@a7i Ah, I see. The test looks good too, thanks.
/approve
/lgtm

**Comment by a7i** [comment]
> Also, would be good to add a test for this. It should probably be an e2e so that the whole config gets tested against (rather than just the eviction logic in a unit test)

Yes, good idea. I will work on that in parallel but may take me a day or two.

**Comment by a7i** [comment]
/retest
Will create an issue if flaky test

**Comment by ingvagabund** [comment]
> Yes, good idea. I will work on that in parallel but may take me a day or two.

Let's do it in this PR as well. Unless it's critical to fix this right away/

**Comment by damemi** [comment]
@ingvagabund I would consider this critical since the strategy crashes in the default use case which causes the entire program to crash. We should merge this asap and release a patch to the v0.22 image.

@a7i will you be able to add the e2e in the next day or so? If not, we can merge this and work on the e2e

**Comment by a7i** [comment]
@damemi yeah I'm working on it... It's not very trivial to force a pod to get a Failed phase.

**Comment by a7i** [comment]
@ingvagabund / @damemi Added a comprehensive set of tests for FailedPods strategy. Kept the commits separate for better organization/tracking.

**Comment by damemi** [comment]
I have no more comments, @ingvagabund do you?

@a7i could you also open a PR to the `release-1.22` branch picking these commits there? Will also need to update the version in the Helm chart to `v0.22.1`

**Comment by ingvagabund** [comment]
@a7i thank you!!!

**Pull request merged**
