### PR TITLE
Update Docs and Manifests for v0.22.0

### PR DESCRIPTION
**Pull request by seanmalloy**
* Added v0.22 references to README
* Update k8s manifests with v0.22.0 references
* Added table with list of supported architectures by release

### CODE REVIEW

**Comment by seanmalloy** [comment]
This should be merged prior to creating the `release-1.22` branch.

/hold

**Comment by seanmalloy** [comment]
It sounds like we are going to do the release soon-ish.

/hold cancel
/assign @damemi

**Review by damemi — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
