### PR TITLE
Delete everything but index.yaml from gh-pages

### PR DESCRIPTION
**Pull request by damemi**
This deletes everything from the `gh-pages` branch except for *index.yaml* which is used to host our helm chart index, as recommended in https://github.com/kubernetes-sigs/descheduler/pull/436#issuecomment-729870148

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/hold
this isn't a total blocker now, just a cleanup. I would also like some other reviewers to double check this change for my sanity :)

/kind cleanup
/cc @seanmalloy 
@stevehipwell

**Comment by seanmalloy** [comment]
This looking correct to me.

1. Merging into the correct branch(gh-pages)
2. All files deleted except for index.yaml
3. No changes to index.yaml

/lgtm

**Comment by stevehipwell** [comment]
Looks correct to me.

**Comment by damemi** [comment]
/hold cancel
thanks for the review

**Pull request merged**
