### PR TITLE
Add Pod Eviction Reason To Events

### PR DESCRIPTION
**Pull request by seanmalloy**
* 7680e3d - minor code refactor
* 4ff533e - add eviction reason to k8s events

Implements #320.

/kind feature

### CODE REVIEW

**Comment by seanmalloy** [comment]
/hold

The code compiles, but I have not tested it yet.

**Comment by seanmalloy** [comment]
/hold cancel
/assign @ingvagabund @damemi 

Successfully tested using `kind` on my laptop. We do not currently have any unit tests or e2e tests for k8s event creation.

```
kubectl get events -n local-path-storage
LAST SEEN   TYPE      REASON              OBJECT                                        MESSAGE
71s         Normal    Descheduled         pod/local-path-provisioner-bd4bb6b75-9p7b9    pod evicted by sigs.k8s.io/descheduler (PodLifeTime)
```

Also ...

This is the second consecutive PR that I've seen where Travis CI is not being triggered. Which means the e2e tests are not being run through CI. :-(

**Comment by seanmalloy** [comment]
Let's see if re-opening the PR will trigger the Travis CI tests.

**Comment by seanmalloy** [comment]
I'm not sure why Travis CI is not triggering. I ran the e2e tests an my laptop using k8s 1.18.2 and the tests pass:
```
make test-e2e
ls: cannot access '_output/bin/golangci-lint': No such file or directory
./test/run-e2e-tests.sh
=== RUN   TestE2E
--- PASS: TestE2E (30.65s)
    e2e_test.go:261: Eviction of pods starting
    e2e_test.go:261: Eviction of pods starting
=== RUN   TestDeschedulingInterval
--- PASS: TestDeschedulingInterval (0.01s)
PASS
ok  	sigs.k8s.io/descheduler/test/e2e	30.851s
```

**Comment by damemi** [comment]
@seanmalloy travis has been acting weird lately. We should try to get our e2e tests on prow as well, is that possible while keeping the backward-compatible version matrix?

**Pull request merged**
