### PR TITLE
cleanup lownodeutilization code

### PR DESCRIPTION
**Pull request by xiaoanyunfei**
The code is duplicated and useless

### CODE REVIEW

**Comment by a7i** [comment]
@xiaoanyunfei thank you for your contribution!

/lgtm
/assign @damemi

**Comment by damemi** [comment]
@a7i or @xiaoanyunfei would you mind opening a PR to revert this? Since the removed log is for targetThresholds, that should still be printed. Maybe update the comment to more clearly indicate that

**Comment by damemi** [comment]
@a7i this is printing both of the thresholds for lownodeutilization. ie, the threshold for nodes that are overutilized as well as the threshold for matching candidate underutilized nodes. so, both should be printed for lownodeutilization.

highnodeutilization only really relies on one threshold since it is focused on bin-packing toward 100% utilization

**Comment by a7i** [comment]
> @a7i this is printing both of the thresholds for lownodeutilization. ie, the threshold for nodes that are overutilized as well as the threshold for matching candidate underutilized nodes. so, both should be printed for lownodeutilization.
> 
> highnodeutilization only really relies on one threshold since it is focused on bin-packing toward 100% utilization

@damemi took a stab at it here:
https://github.com/kubernetes-sigs/descheduler/pull/830

**Pull request merged**
