### PR TITLE
HighNodeutilisation strategy

### LINKED ISSUE #196: Add HighNodeUtilization strategy
I want to keep my cluster as compact as possible. In order to do that, I switched kubernetes-scheduler policy from LeastRequestedPriority to MostRequestedPriority. It would be greate to have corresponding HighNodeUtilization strategy for descheduler.

### PR DESCRIPTION
**Pull request by hanumanthan**
Adding HighNodeutilisation strategy. Accepts `threshold` and `targetThreshold` as parameter configs.
Eliminate pods from nodes under `targetThreshold` and places them in nodes between `threshold` and `targetThreshold`. 
This works in tandem in scheduler config of `MostRequestedPriority` such that pods are placed in nodes with high utilization.

Functions common to High and LowNode Utilization strategies have been extracted to a seperate file.

Pending
1. E2E tests
2. Docs update
3. Config updates

Fixes #196

### CODE REVIEW

**Comment by ingvagabund** [comment]
@hanumanthan thanks for the PR. Can you break the PR into more commits? E.g.
1. moving common code into separate file
2. renaming
3. new strategy
4. tests for the new strategy
5. ...

So it's easier to review. Thanks!!!

**Comment by hanumanthan** [comment]
> @hanumanthan thanks for the PR. Can you break the PR into more commits? E.g.
> 
> 1. moving common code into separate file
> 2. renaming
> 3. new strategy
> 4. tests for the new strategy
> 5. ...
> 
> So it's easier to review. Thanks!!!

@ingvagabund This commit seperation is slightly difficult to achieve as i started writing `highnodeutilization` and only moved common functions to seperate file on a need basis.

However the 1st commit is more focused towards this refractor and creating the new strategy while 2nd commit was the tests and fine tuning the `highnodeutilization`. 
If you still prefer it that way then I will have to create a new PR and make those new changes. Lemme know if there is an easier way

**Comment by ingvagabund** [comment]
> If you still prefer

I do. Sorry for any inconvenience.

**Comment by hanumanthan** [comment]
I needed a new branch to create all those commits so I keep this branch untouched for my reference. So opened a new PR https://github.com/kubernetes-sigs/descheduler/pull/341. 

Closing this

**Pull request closed without merging**
