### PR TITLE
Add handling for node eligibility

### PR DESCRIPTION
**Pull request by MarcPow**
Proposing a potential fix for #1204.

Looking for feedback before adding unit tests, etc.

The current code assumes that a couple of beta feature flags around are currently enabled by default.

### CODE REVIEW

**Comment by damemi** [comment]
/ok-to-test
thanks @MarcPow, I understand wanting to hold off on adding tests but it would be helpful to understand the change if you could add a couple test cases to demonstrate

**Comment by a7i** [comment]
Thank you @MarcPow for this change, looks very thorough.

However, we are planning on introducing a `NodeFitSpec` that will give more flexibility as to what thing to check in order to identify eligible nodes.

Please see [this comment](https://github.com/kubernetes-sigs/descheduler/issues/1149#issuecomment-1576478347) on the Issue. What do you think?

**Comment by MarcPow** [comment]
> Thank you @MarcPow for this change, looks very thorough.
> 
> However, we are planning on introducing a `NodeFitSpec` that will give more flexibility as to what thing to check in order to identify eligible nodes.
> 
> Please see [this comment](https://github.com/kubernetes-sigs/descheduler/issues/1149#issuecomment-1576478347) on the Issue. What do you think?

I think we're all on the same page with respect to the need.   The original proposal was a good one, but I think it was made independent of / prior to the changes that happened in the podTopologySpreadConstraints spec that added more controls here.  At the point that those behaviors were added, I think the call on the descheduler is simply to behave just as the scheduler itself would when placing the pods in the first place.  An independent, separate policy has thus become unnecessary.

**Pull request closed without merging**
