### PR TITLE
refactor: remove unused code

### PR DESCRIPTION
**Pull request by Mathew857**
/kind design

ReadyNodes's  parm about 'stopChannel' is not being used

### CODE REVIEW

**Comment by Mathew857** [comment]
/assign @damemi 

please help reviewd when you are free, thanks a lot

**Review by damemi — APPROVED** [review]
/approve
good find, looks like this was missed when we updated the node informer code in this commit: https://github.com/kubernetes-sigs/descheduler/commit/9593ce16d96f3d1f7c10a7cc34eb7cd0b64e38d6#diff-fc4033754cd376d78b09ff84a934296f26e774702505885309268f816ba3817c

**Comment by damemi** [comment]
@Mathew857 looks like you also need to update the test files:
```
 # sigs.k8s.io/descheduler/pkg/descheduler/node [sigs.k8s.io/descheduler/pkg/descheduler/node.test]
pkg/descheduler/node/node_test.go:77:24: too many arguments in call to ReadyNodes
	have (context.Context, *"k8s.io/client-go/kubernetes/fake".Clientset, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
	want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string) 
```

**Comment by Mathew857** [comment]
> @Mathew857 looks like you also need to update the test files:
> 
> ```
>  # sigs.k8s.io/descheduler/pkg/descheduler/node [sigs.k8s.io/descheduler/pkg/descheduler/node.test]
> pkg/descheduler/node/node_test.go:77:24: too many arguments in call to ReadyNodes
> 	have (context.Context, *"k8s.io/client-go/kubernetes/fake".Clientset, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
> 	want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string) 
> ```

ok, I'll update ASAP

**Comment by Mathew857** [comment]
/assign @damemi 

node_test file updated, pls check it if you are free, thanks a lot

**Comment by Mathew857** [comment]
"skipped 213 lines unfold_more
	have (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
	want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string)
test/e2e/e2e_test.go:197:35: too many arguments in call to "sigs.k8s.io/descheduler/pkg/descheduler/node".ReadyNodes
	have (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
	want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string)
========
"


should I also  refactor  about node informer code  in client-go ? @damemi

**Comment by Mathew857** [comment]
should I also refactor about node informer code in client-go ? @damemi



"skipped 213 lines unfold_more
have (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string)
test/e2e/e2e_test.go:197:35: too many arguments in call to "sigs.k8s.io/descheduler/pkg/descheduler/node".ReadyNodes
have (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string, nil)
want (context.Context, kubernetes.Interface, "k8s.io/client-go/informers/core/v1".NodeInformer, string)"

**Comment by damemi** [comment]
@Mathew857 that error looks to just be a similar one, this time in `test/e2e/e2e_test.go`, just need to remove this param from `ReadyNodes` there too

**Comment by Mathew857** [comment]
> @Mathew857 that error looks to just be a similar one, this time in `test/e2e/e2e_test.go`, just need to remove this param from `ReadyNodes` there too

thanks reminder

**Review by lixiang233 — COMMENTED** [review]
/lgtm

**Pull request merged**
