### PR TITLE
Bump k8s deps to 1.17

### LINKED ISSUE #203: Bump to kubernetes 1.17.0
Now that 1.17 is released, once `kubernetes-1.17.0` tags are available in dependency repos (such as k/apimachinery and k/client-go), we should update our pinned dependencies to that version

### PR DESCRIPTION
**Pull request by damemi**
Fixes #203

### CODE REVIEW

**Comment by damemi** [comment]
This is ready for review/approval

**Comment by aveshagarwal** [comment]
could you resolve conflicts?

**Comment by damemi** [comment]
@aveshagarwal yup, fixed

**Comment by aveshagarwal** [comment]
thanks @damemi .

/approve

**Comment by aveshagarwal** [comment]
is it ready to be merged?

**Comment by damemi** [comment]
@aveshagarwal yes, just needs an /lgtm tag

**Comment by aveshagarwal** [comment]
/lgtm

thanks @damemi

**Pull request merged**
