### PR TITLE
k8s 1.27: update docs and README

### LINKED ISSUE #1080: Update version references in docs and readme

### PR DESCRIPTION
**Pull request by a7i**
Closes #1080

### CODE REVIEW

**Comment by ingvagabund** [comment]
Let's wait here until we decide at which commit we branch

**Comment by a7i** [comment]
/hold

I also need #1110 merged so I can rebase

**Comment by a7i** [comment]
@damemi tag has been created

**Comment by damemi** [comment]
> @damemi tag has been created

Awesome, thanks! Merging this so we can get a build for v0.27. Then we just need the image promotion, and that will unblock the Helm PRs
/approve
/lgtm

**Pull request merged**
