### PR TITLE
feat: Add EvictionStrategy option for DeschedulerPolicy

### PR DESCRIPTION
**Pull request by lianghao208**
fix: #690 

According to the discussion in https://github.com/kubernetes-sigs/descheduler/issues/690

Pods eviction may cause pods sharing the same priority and QoS class to be evicted over and over. Because pods are in alphabetically order in podIndexer.

If pods share the same priority and QoS class, the older pods should be more likely to be evicted.

### CODE REVIEW

**Comment by knelasevero** [comment]
@a7i @ingvagabund @damemi with the new framework/plugin approach, this PR could be a new custom plugin, am I right? Is this PR now obsolete with the latest changes in the descheduler?

**Comment by damemi** [comment]
> @a7i @ingvagabund @damemi with the new framework/plugin approach, this PR could be a new custom plugin, am I right? Is this PR now obsolete with the latest changes in the descheduler?

Yeah, this change would be better as a Sorting plugin in the new framework code

**Comment by knelasevero** [comment]
We let the bot close the issue, but we left the PR open? What's the plan here?

**Pull request closed without merging**
