### PR TITLE
Update klog to v2

### LINKED ISSUE #286: Update To klog v2
The upstream k8s project has updated from klog v1 to klog v2. At some point in time the descheduler should also update to klog v2.

References
* https://github.com/kubernetes/kubernetes/pull/90183
* https://github.com/kubernetes/enhancements/pull/1617

### PR DESCRIPTION
**Pull request by farah**
Updates klog to v2

Fixes #286

### CODE REVIEW

**Comment by farah** [comment]
sorry, I'll review this.

**Comment by seanmalloy** [comment]
> sorry, should have run e2e tests locally first. 

@farah no problem. Please let us know if you have any questions or need any help with the test failures.

**Comment by ingvagabund** [comment]
Running `./hack/update-vendor.sh` will do.

**Comment by farah** [comment]
@ingvagabund thanks for the tip.

**Comment by ingvagabund** [comment]
https://travis-ci.org/github/kubernetes-sigs/descheduler/builds/700840377 is green.

Also no more `"k8s.io/klog"` imports in pkg directory:
```
$ grep -rn '"k8s.io/klog"'
vendor/k8s.io/utils/trace/trace.go:25:	"k8s.io/klog"
vendor/k8s.io/component-base/cli/flag/flags.go:24:	"k8s.io/klog"
vendor/k8s.io/component-base/featuregate/feature_gate.go:30:	"k8s.io/klog"
vendor/k8s.io/component-base/logs/logs.go:27:	"k8s.io/klog"
vendor/k8s.io/client-go/transport/round_trippers.go:26:	"k8s.io/klog"
vendor/k8s.io/client-go/transport/transport.go:30:	"k8s.io/klog"
vendor/k8s.io/client-go/transport/token_source.go:29:	"k8s.io/klog"
vendor/k8s.io/client-go/transport/cert_rotation.go:32:	"k8s.io/klog"
vendor/k8s.io/client-go/rest/config.go:40:	"k8s.io/klog"
vendor/k8s.io/client-go/rest/urlbackoff.go:25:	"k8s.io/klog"
vendor/k8s.io/client-go/rest/request.go:48:	"k8s.io/klog"
vendor/k8s.io/client-go/rest/plugin.go:24:	"k8s.io/klog"
vendor/k8s.io/client-go/listers/policy/v1beta1/poddisruptionbudget_expansion.go:26:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/clientcmd/loader.go:31:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/clientcmd/config.go:27:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/clientcmd/client_config.go:28:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:23:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/delta_fifo.go:26:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/reflector.go:42:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/expiration_cache.go:24:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/listers.go:20:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/shared_informer.go:31:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/mutation_cache.go:25:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/cache/mutation_detector.go:27:	"k8s.io/klog"
vendor/k8s.io/client-go/tools/record/event.go:34:	"k8s.io/klog"
vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go:49:	"k8s.io/klog"
vendor/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack.go:27:	"k8s.io/klog"
vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go:36:	"k8s.io/klog"
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:31:	"k8s.io/klog"
vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:34:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/labels/selector.go:29:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/util/net/interface.go:29:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/util/net/http.go:35:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go:29:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go:29:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:26:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:30:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/api/meta/meta.go:28:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/runtime/converter.go:36:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/runtime/codec.go:32:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:34:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:28:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:24:	"k8s.io/klog"
vendor/k8s.io/apimachinery/pkg/watch/watch.go:23:	"k8s.io/klog"
```

Unit tests still kloging:
```
$ go test -v sigs.k8s.io/descheduler/pkg/descheduler/strategies -run TestFindDuplicatePods
=== RUN   TestFindDuplicatePods
I0622 13:56:32.756822   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.756957   23913 evictions.go:148] Evicted pod: "p2" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757020   23913 evictions.go:148] Evicted pod: "p3" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757047   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757071   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757102   23913 evictions.go:148] Evicted pod: "p9" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757157   23913 evictions.go:148] Evicted pod: "p10" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757184   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757222   23913 evictions.go:148] Evicted pod: "p2" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757243   23913 evictions.go:148] Evicted pod: "p3" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757263   23913 evictions.go:148] Evicted pod: "p9" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757294   23913 evictions.go:148] Evicted pod: "p10" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757314   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757340   23913 evictions.go:105] Pod p4 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: pod is a DaemonSet pod
I0622 13:56:32.757359   23913 evictions.go:105] Pod p5 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: pod has local storage and descheduler is not configured with --evict-local-storage-pods
I0622 13:56:32.757389   23913 evictions.go:105] Pod p6 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: [pod is critical, pod does not have any ownerrefs, pod is a mirror pod]
I0622 13:56:32.757394   23913 evictions.go:105] Pod p7 in namespace kube-system is not evictable: Pod lacks an eviction annotation and fails the following checks: [pod is critical, pod does not have any ownerrefs]
I0622 13:56:32.757399   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757433   23913 evictions.go:105] Pod p4 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: pod is a DaemonSet pod
I0622 13:56:32.757439   23913 evictions.go:105] Pod p5 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: pod has local storage and descheduler is not configured with --evict-local-storage-pods
I0622 13:56:32.757447   23913 evictions.go:105] Pod p6 in namespace default is not evictable: Pod lacks an eviction annotation and fails the following checks: [pod is critical, pod does not have any ownerrefs, pod is a mirror pod]
I0622 13:56:32.757452   23913 evictions.go:105] Pod p7 in namespace kube-system is not evictable: Pod lacks an eviction annotation and fails the following checks: [pod is critical, pod does not have any ownerrefs]
I0622 13:56:32.757463   23913 evictions.go:148] Evicted pod: "p2" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757497   23913 evictions.go:148] Evicted pod: "p3" in namespace "dev" (RemoveDuplicatePods)
I0622 13:56:32.757523   23913 evictions.go:148] Evicted pod: "p9" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757576   23913 evictions.go:148] Evicted pod: "p10" in namespace "test" (RemoveDuplicatePods)
I0622 13:56:32.757604   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757631   23913 duplicates.go:58] Processing node: "n1"
I0622 13:56:32.757648   23913 duplicates.go:58] Processing node: "n1"
--- PASS: TestFindDuplicatePods (0.00s)
PASS
ok  	sigs.k8s.io/descheduler/pkg/descheduler/strategies	0.012s
```

/lgtm

**Comment by damemi** [comment]
This change appears to have broken logging, see https://github.com/kubernetes-sigs/descheduler/issues/353

If a quick fix can't be identified, we will revert this change for 1.19

**Pull request merged**
