### PR TITLE
dry-run cli flag to use uppercase

### PR DESCRIPTION
**Pull request by yanggangtony**
.

### CODE REVIEW

**Comment by a7i** [comment]
/retitle dry-run cli flag to use uppercase
/ok-to-test
/lgtm

**Comment by a7i** [comment]
@yanggangtony  would you please update the docs by running the make commands?

**Comment by yanggangtony** [comment]
@a7i 
Thanks for the review and quick response.
Rebased it.

**Comment by a7i** [comment]
/lgtm
/approve

Thank you for your contribution!

**Pull request merged**
