### PR TITLE
Bump To Go 1.15.2

### LINKED ISSUE #415: Update To Go 1.15.2
It's time to update Go versions again.In the k/k repo 1.19 and 1.20 have been updated to Go 1.15.2.

https://github.com/kubernetes/kubernetes/pull/94449

### PR DESCRIPTION
**Pull request by seanmalloy**
Fixes #415

### CODE REVIEW

**Comment by seanmalloy** [comment]
/hold

Wait until https://github.com/kubernetes/test-infra/pull/19434 is merged.

**Review by damemi — APPROVED** [review]
/approve

**Pull request merged**
