### PR TITLE
Avoid unnecessary aborting

### PR DESCRIPTION
**Pull request by lixiang233**
fixes: #469

### CODE REVIEW

**Comment by aveshagarwal** [comment]
/hold

I will leave a comment in the issue to describe what was the intended design of having node selector initially.

**Comment by aveshagarwal** [comment]
Feel free to cancel hold, as far as the intended design of node selector is clear and any change does not affect some of the strategies like LowNodeUtilization.

**Review by damemi — COMMENTED** [review]
I agree that we should think more about this, because the points @aveshagarwal raised in the issue about this affecting certain strategies are valid.

What if we log a warningf that running LowNodeUtilization over 1 node-selector is not performant? We could also disable LNU if it's enabled.

Are there any other strategies we should take into consideration that would be hurt by this?

**Comment by lixiang233** [comment]
I think we do not need this PR given #488  has a better way to do this.
/close

**Comment by damemi** [comment]
@lixiang233 does #488 affect the questions here? I thought this PR was more about considering the difference between node selector scope for various strategies

**Comment by lixiang233** [comment]
@damemi  I think we can list and filter nodes in each strategies when running descheduler in `Informed` mode, so every strategies can custom `nodeSelector` and handle boundary cases as needed. Or if we want to add this feature for `Default` mode too, I can reopen this PR and complete it as what was suggested in [this comment](https://github.com/kubernetes-sigs/descheduler/issues/469#issuecomment-763413379).

**Comment by damemi** [comment]
Ah, that's fair enough. I think it would be worth it to fix this up in both approaches, but overall this isn't a critical bug

**Pull request closed without merging**
