### PR TITLE
Release 1.28.1

### PR DESCRIPTION
**Pull request by a7i**
Step 1 in the release step for v0.28.1
https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md#flowchart

### CODE REVIEW

**Comment by JaneLiuL** [comment]
thanks @a7i , when you finish an squash the commits please let me know

**Comment by a7i** [comment]
Hi @JaneLiuL we do not squash cherry-picks / release branches

**Comment by JaneLiuL** [comment]
thanks, @a7i  , when you finish please let me know~~

**Comment by a7i** [comment]
> thanks, @a7i  , when you finish please let me know~~ 

Thanks@JaneLiuL it is ready for review

**Review by JaneLiuL — COMMENTED** [review]
/lgtm

**Comment by knelasevero** [comment]
/approve
sorry for long delay!

**Pull request merged**
