### PR TITLE
v0.29.0: bump helm chart and update manifests/docs

### LINKED ISSUE #1320: 1.29: Update version references in docs and readme

### PR DESCRIPTION
**Pull request by a7i**
Needs: https://github.com/kubernetes/k8s.io/pull/6236

Closes #1320 and #1326

### CODE REVIEW

**Comment by damemi** [comment]
```
./hack/verify-conversions.sh
Generated output differs:
diff -Naupr pkg/api/v1alpha2/zz_generated.conversion.go ./hack/../_tmp/kube-verify.C1Z0Aa/descheduler/pkg/api/v1alpha2/zz_generated.conversion.go
--- pkg/api/v1alpha2/zz_generated.conversion.go	2024-01-02 13:30:13.599941786 +0000
+++ ./hack/../_tmp/kube-verify.C1Z0Aa/descheduler/pkg/api/v1alpha2/zz_generated.conversion.go	2024-01-02 13:35:31.609973450 +0000
@@ -2,7 +2,7 @@
 // +build !ignore_autogenerated
 
 /*
-Copyright 2023 The Kubernetes Authors.
+Copyright 2024 The Kubernetes Authors.
```

Happy new year! 🎉

**Comment by a7i** [comment]
@damemi PR is ready for review

**Review by damemi — COMMENTED** [review]
/approve

**Pull request merged**
