### PR TITLE
Bump to k8s 1.24.0

### PR DESCRIPTION
**Pull request by JaneLiuL**

### CODE REVIEW

**Comment by JaneLiuL** [comment]
need pr:  https://github.com/kubernetes/test-infra/pull/25833 merge first

**Review by damemi — COMMENTED** [review]
Thanks @JaneLiuL! There's just a couple changes needed in the test-infra PR then I think we'll want to close and reopen this PR to pick up the new master branch CI tests. But this looks good to me, I'm just going to hold it so we don't accidentally merge before then.
/approve
/hold

**Comment by dineshbhor** [comment]
Any estimated release date for the 1.24 descheduler image? Actually, we are waiting for it. Thanks.

**Comment by damemi** [comment]
> Any estimated release date for the 1.24 descheduler image? Actually, we are waiting for it. Thanks.

@dineshbhor it will be available soon, we just need https://github.com/kubernetes-sigs/descheduler/pull/795 to merge and fix CI and we should be able to finish cutting the release (including this PR) either this or next week

**Comment by dineshbhor** [comment]
@damemi 

> @dineshbhor it will be available soon, we just need https://github.com/kubernetes-sigs/descheduler/pull/795 to merge and fix CI and we should be able to finish cutting the release (including this PR) either this or next week

Thanks for the clarification. Tag is created but the new release is not published yet?

**Pull request merged**
