### PR TITLE
Update e2e tests to use kind v0.10.0

### PR DESCRIPTION
**Pull request by seanmalloy**

### CODE REVIEW

**Comment by seanmalloy** [comment]
I submitted https://github.com/kubernetes/test-infra/pull/21019 to update the e2e test to use the latest k8s versions.

/hold

**Comment by ingvagabund** [comment]
```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.20.2) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
```

```

Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.19.7) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.19.7) 🖼
```

```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.18.15) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.18.15) 🖼
```

**Review by damemi — APPROVED** [review]
/approve

**Pull request merged**
