### PR TITLE
bump k8s.io libs to v0.31.0

### PR DESCRIPTION
**Pull request by a7i**
Closes https://github.com/kubernetes-sigs/descheduler/issues/1487

In a follow-up PR we need to decide between our custom `--enable-http2` vs `--disable-http2-serving`

### CODE REVIEW

**Comment by jklaw90** [comment]
Fwiw I like `--disable-http2-serving`

**Comment by a7i** [comment]
> Fwiw I like `--disable-http2-serving`

Any suggestions on how we deprecate our custom flag?

My thinking is to make it optional/nil with a deprecated message. And then remove in 2 releases?

**Comment by ingvagabund** [comment]
I will have another review capacity beg of the next week if that's ok.

**Comment by a7i** [comment]
> I will have another review capacity beg of the next week if that's ok.

sounds good, I'll have that PR ready by then. for now, I'll get this merged since it's standard upgrade changes

**Pull request merged**
