### PR TITLE
includeSoftConstraints not being respected for TopologySpreadConstraint

### PR DESCRIPTION
**Pull request by vholer**
Issue #960

Signed-off-by: Vlastimil Holer <vh@fortrabbit.com>

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test
@ingvagabund or @knelasevero could we add an e2e for this?

**Comment by ingvagabund** [comment]
> could we add an e2e for this?

The affected code will get removed eventually. The code under strategy_migration.go file will get re-implemented. So any sort of testing will be only temporary. I will pass this.

**Comment by a7i** [comment]
@damemi @ingvagabund Unfortunately our e2e tests are calling the strategy directly (and therefore bypassing the strategy migration). In an ideal world, e2e would be end-to-end testing that would catch it.

I'll think about this some more on how we can modify our e2e but if you have any ideas, let me know.

**Pull request merged**
